# Generated by Django 3.1.4 on 2021-02-03 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='year',
            field=models.IntegerField(),
        ),
    ]
