# Generated by Django 3.1.4 on 2021-10-21 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0003_auto_20210921_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='link',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='experience',
            name='location',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='experience',
            name='company',
            field=models.TextField(default=''),
        ),
    ]
