# Generated by Django 3.1.4 on 2021-10-21 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0004_auto_20211021_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='company',
            field=models.TextField(blank=True),
        ),
    ]
