# Generated by Django 3.1.4 on 2021-11-06 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0005_auto_20211021_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='description',
            field=models.TextField(default=True),
        ),
    ]
