# Generated by Django 3.1.4 on 2021-09-07 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='end_date',
            field=models.IntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.IntegerField(default=''),
        ),
    ]
