# Generated by Django 3.1.4 on 2021-09-07 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_auto_20210907_1036'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='end_date',
            new_name='year',
        ),
        migrations.RemoveField(
            model_name='project',
            name='start_date',
        ),
    ]
