# Generated by Django 3.1.4 on 2021-10-21 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_auto_20210907_1120'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='link',
            new_name='github_icon',
        ),
        migrations.AddField(
            model_name='project',
            name='github_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='project_link',
            field=models.URLField(blank=True),
        ),
    ]
