# Generated by Django 3.1.4 on 2021-10-21 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_auto_20211021_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='github_icon',
            field=models.TextField(blank=True),
        ),
    ]
