# Generated by Django 3.1.4 on 2021-10-21 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_auto_20211021_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='disclaimer',
            field=models.TextField(blank=True),
        ),
    ]
