# Generated by Django 3.1.4 on 2021-11-02 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0010_project_disclaimer'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='improvements',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='project',
            name='learned',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='project',
            name='reflection',
            field=models.TextField(default=''),
        ),
    ]
