# Generated by Django 3.1.4 on 2021-11-03 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0012_topicslearnedlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='learned',
        ),
    ]
