# Generated by Django 3.1.4 on 2021-11-03 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0013_remove_project_learned'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='class_event',
            field=models.TextField(blank=True),
        ),
    ]
